import streamlit as st
from streamlit_tree_select import tree_select

def test_function():
    # Create nodes to display
    nodes = [
                {
                    "label": "Filters",
                    "value": "all",
                    "children": [

                        {
                            "label": "Automotive",
                            "value": "Automotive",
                            "children": [
                                {"label": "car_dealer", "value": "car_dealer"},
                                {"label": "car_rental", "value": "car_rental"},
                                {"label": "car_repair", "value": "car_repair"},
                                {"label": "car_wash", "value": "car_wash"},
                                {"label": "electric_vehicle_charging_station", "value": "electric_vehicle_charging_station"},
                                {"label": "gas_station", "value": "gas_station"},
                                {"label": "parking", "value": "parking"},
                                {"label": "rest_stop", "value": "rest_stop"}
                            ],
                        },

                        {
                            "label": "Business",
                            "value": "Business",
                            "children": [
                                {"label": "corporate_office", "value": "corporate_office"},
                                {"label": "farm", "value": "farm"}, 
                                {"label": "ranch", "value": "ranch"}
                            ],
                        },

                        {
                            "label": "Culture",
                            "value": "Culture",
                            "children": [
                                {"label": "art_gallery", "value": "art_gallery"},
                                {"label": "art_studio", "value": "art_studio"},
                                {"label": "auditorium", "value": "auditorium"},
                                {"label": "cultural_landmark", "value": "cultural_landmark"},
                                {"label": "historical_place", "value": "historical_place"},
                                {"label": "monument", "value": "monument"},
                                {"label": "museum", "value": "museum"},
                                {"label": "performing_arts_theater", "value": "performing_arts_theater"},
                                {"label": "sculpture", "value": "sculpture"}
                            ],
                        },

                        {
                            "label": "Education",
                            "value": "Education",
                            "children": [
                                {"label": "library", "value": "library"},
                                {"label": "preschool", "value": "preschool"},
                                {"label": "primary_school", "value": "primary_school"},
                                {"label": "school", "value": "school"},
                                {"label": "secondary_school", "value": "secondary_school"},
                                {"label": "university", "value": "university"}
                            ],
                        },

                        {
                            "label": "Entertainment and Recreation",
                            "value": "Entertainment and Recreation",
                            "children": [
                                {"label": "adventure_sports_center", "value": "adventure_sports_center"},
                                {"label": "amphitheatre", "value": "amphitheatre"},
                                {"label": "amusement_center", "value": "amusement_center"},
                                {"label": "amusement_park", "value": "amusement_park"},
                                {"label": "aquarium", "value": "aquarium"},
                                {"label": "banquet_hall", "value": "banquet_hall"},
                                {"label": "barbecue_area", "value": "barbecue_area"},
                                {"label": "botanical_garden", "value": "botanical_garden"},
                                {"label": "bowling_alley", "value": "bowling_alley"},
                                {"label": "casino", "value": "casino"},
                                {"label": "childrens_camp", "value": "childrens_camp"},
                                {"label": "comedy_club", "value": "comedy_club"},
                                {"label": "community_center", "value": "community_center"},
                                {"label": "concert_hall", "value": "concert_hall"},
                                {"label": "convention_center", "value": "convention_center"},
                                {"label": "cultural_center", "value": "cultural_center"},
                                {"label": "cycling_park", "value": "cycling_park"},
                                {"label": "dance_hall", "value": "dance_hall"},
                                {"label": "dog_park", "value": "dog_park"},
                                {"label": "event_venue", "value": "event_venue"},
                                {"label": "ferris_wheel", "value": "ferris_wheel"},
                                {"label": "garden", "value": "garden"},
                                {"label": "hiking_area", "value": "hiking_area"},
                                {"label": "historical_landmark", "value": "historical_landmark"},
                                {"label": "internet_cafe", "value": "internet_cafe"},
                                {"label": "karaoke", "value": "karaoke"},
                                {"label": "marina", "value": "marina"},
                                {"label": "movie_rental", "value": "movie_rental"},
                                {"label": "movie_theater", "value": "movie_theater"},
                                {"label": "national_park", "value": "national_park"},
                                {"label": "night_club", "value": "night_club"},
                                {"label": "observation_deck", "value": "observation_deck"},
                                {"label": "off_roading_area", "value": "off_roading_area"},
                                {"label": "opera_house", "value": "opera_house"},
                                {"label": "park", "value": "park"},
                                {"label": "philharmonic_hall", "value": "philharmonic_hall"},
                                {"label": "picnic_ground", "value": "picnic_ground"},
                                {"label": "planetarium", "value": "planetarium"},
                                {"label": "plaza", "value": "plaza"},
                                {"label": "roller_coaster", "value": "roller_coaster"},
                                {"label": "skateboard_park", "value": "skateboard_park"},
                                {"label": "state_park", "value": "state_park"},
                                {"label": "tourist_attraction", "value": "tourist_attraction"},
                                {"label": "video_arcade", "value": "video_arcade"},
                                {"label": "visitor_center", "value": "visitor_center"},
                                {"label": "water_park", "value": "water_park"},
                                {"label": "wedding_venue", "value": "wedding_venue"},
                                {"label": "wildlife_park", "value": "wildlife_park"},
                                {"label": "wildlife_refuge", "value": "wildlife_refuge"},
                                {"label": "zoo", "value": "zoo"}
                            ],
                        },

                        {
                            "label": "Facilities",
                            "value": "Facilities",
                            "children": [
                                {"label": "public_bath", "value": "public_bath"},
                                {"label": "public_bathroom", "value": "public_bathroom"},
                                {"label": "stable", "value": "stable"}
                            ],
                        },

                        {
                            "label": "Finance",
                            "value": "Finance",
                            "children": [
                                {"label": "accounting", "value": "accounting"},
                                {"label": "atm", "value": "atm"},
                                {"label": "bank", "value": "bank"}
                            ],
                        },

                        {
                            "label": "Food and Drink",
                            "value": "Food and Drink",
                            "children": [
                                {"label": "acai_shop", "value": "acai_shop"},
                                {"label": "afghani_restaurant", "value": "afghani_restaurant"},
                                {"label": "african_restaurant", "value": "african_restaurant"},
                                {"label": "american_restaurant", "value": "american_restaurant"},
                                {"label": "asian_restaurant", "value": "asian_restaurant"},
                                {"label": "bagel_shop", "value": "bagel_shop"},
                                {"label": "bakery", "value": "bakery"},
                                {"label": "bar", "value": "bar"},
                                {"label": "bar_and_grill", "value": "bar_and_grill"},
                                {"label": "barbecue_restaurant", "value": "barbecue_restaurant"},
                                {"label": "brazilian_restaurant", "value": "brazilian_restaurant"},
                                {"label": "breakfast_restaurant", "value": "breakfast_restaurant"},
                                {"label": "brunch_restaurant", "value": "brunch_restaurant"},
                                {"label": "buffet_restaurant", "value": "buffet_restaurant"},
                                {"label": "cafe", "value": "cafe"},
                                {"label": "cafeteria", "value": "cafeteria"},
                                {"label": "candy_store", "value": "candy_store"},
                                {"label": "cat_cafe", "value": "cat_cafe"},
                                {"label": "chinese_restaurant", "value": "chinese_restaurant"},
                                {"label": "chocolate_factory", "value": "chocolate_factory"},
                                {"label": "chocolate_shop", "value": "chocolate_shop"},
                                {"label": "coffee_shop", "value": "coffee_shop"},
                                {"label": "confectionery", "value": "confectionery"},
                                {"label": "deli", "value": "deli"},
                                {"label": "dessert_restaurant", "value": "dessert_restaurant"},
                                {"label": "dessert_shop", "value": "dessert_shop"},
                                {"label": "diner", "value": "diner"},
                                {"label": "dog_cafe", "value": "dog_cafe"},
                                {"label": "donut_shop", "value": "donut_shop"},
                                {"label": "fast_food_restaurant", "value": "fast_food_restaurant"},
                                {"label": "fine_dining_restaurant", "value": "fine_dining_restaurant"},
                                {"label": "food_court", "value": "food_court"},
                                {"label": "french_restaurant", "value": "french_restaurant"},
                                {"label": "greek_restaurant", "value": "greek_restaurant"},
                                {"label": "hamburger_restaurant", "value": "hamburger_restaurant"},
                                {"label": "ice_cream_shop", "value": "ice_cream_shop"},
                                {"label": "indian_restaurant", "value": "indian_restaurant"},
                                {"label": "indonesian_restaurant", "value": "indonesian_restaurant"},
                                {"label": "italian_restaurant", "value": "italian_restaurant"},
                                {"label": "japanese_restaurant", "value": "japanese_restaurant"},
                                {"label": "juice_shop", "value": "juice_shop"},
                                {"label": "korean_restaurant", "value": "korean_restaurant"},
                                {"label": "lebanese_restaurant", "value": "lebanese_restaurant"},
                                {"label": "meal_delivery", "value": "meal_delivery"},
                                {"label": "meal_takeaway", "value": "meal_takeaway"},
                                {"label": "mediterranean_restaurant", "value": "mediterranean_restaurant"},
                                {"label": "mexican_restaurant", "value": "mexican_restaurant"},
                                {"label": "middle_eastern_restaurant", "value": "middle_eastern_restaurant"},
                                {"label": "pizza_restaurant", "value": "pizza_restaurant"},
                                {"label": "pub", "value": "pub"},
                                {"label": "ramen_restaurant", "value": "ramen_restaurant"},
                                {"label": "restaurant", "value": "restaurant"},
                                {"label": "sandwich_shop", "value": "sandwich_shop"},
                                {"label": "seafood_restaurant", "value": "seafood_restaurant"},
                                {"label": "spanish_restaurant", "value": "spanish_restaurant"},
                                {"label": "steak_house", "value": "steak_house"},
                                {"label": "sushi_restaurant", "value": "sushi_restaurant"},
                                {"label": "tea_house", "value": "tea_house"},
                                {"label": "thai_restaurant", "value": "thai_restaurant"},
                                {"label": "turkish_restaurant", "value": "turkish_restaurant"},
                                {"label": "vegan_restaurant", "value": "vegan_restaurant"},
                                {"label": "vegetarian_restaurant", "value": "vegetarian_restaurant"},
                                {"label": "vietnamese_restaurant", "value": "vietnamese_restaurant"},
                                {"label": "wine_bar", "value": "wine_bar"},
                            ],
                        },

                        {
                            "label": "Geographical Areas",
                            "value": "Geographical Areas",
                            "children": [
                                {"label": "administrative_area_level_1", "value": "administrative_area_level_1"},
                                {"label": "administrative_area_level_2", "value": "administrative_area_level_2"},
                                {"label": "country", "value": "country"},
                                {"label": "locality", "value": "locality"},
                                {"label": "postal_code", "value": "postal_code"},
                                {"label": "school_district", "value": "school_district"}
                            ],
                        },

                        {
                            "label": "Government",
                            "value": "Government",
                            "children": [
                                {"label": "city_hall", "value": "city_hall"},
                                {"label": "courthouse", "value": "courthouse"},
                                {"label": "embassy", "value": "embassy"},
                                {"label": "fire_station", "value": "fire_station"},
                                {"label": "government_office", "value": "government_office"},
                                {"label": "local_government_office", "value": "local_government_office"},
                                {"label": "neighborhood_police_station (Japan only)", "value": "neighborhood_police_station"},
                                {"label": "police", "value": "police"},
                                {"label": "post_office", "value": "post_office"}
                            ],
                        },

                        {
                            "label": "Health and Wellness",
                            "value": "Health and Wellness",
                            "children": [
                                {"label": "chiropractor", "value": "chiropractor"},
                                {"label": "dental_clinic", "value": "dental_clinic"},
                                {"label": "dentist", "value": "dentist"},
                                {"label": "doctor", "value": "doctor"},
                                {"label": "drugstore", "value": "drugstore"},
                                {"label": "hospital", "value": "hospital"},
                                {"label": "massage", "value": "massage"},
                                {"label": "medical_lab", "value": "medical_lab"},
                                {"label": "pharmacy", "value": "pharmacy"},
                                {"label": "physiotherapist", "value": "physiotherapist"},
                                {"label": "sauna", "value": "sauna"},
                                {"label": "skin_care_clinic", "value": "skin_care_clinic"},
                                {"label": "spa", "value": "spa"},
                                {"label": "tanning_studio", "value": "tanning_studio"},
                                {"label": "wellness_center", "value": "wellness_center"},
                                {"label": "yoga_studio", "value": "yoga_studio"}
                            ],
                        },

                        {
                            "label": "Housing",
                            "value": "Housing",
                            "children": [
                                {"label": "apartment_building", "value": "apartment_building"},
                                {"label": "apartment_complex", "value": "apartment_complex"},
                                {"label": "condominium_complex", "value": "condominium_complex"},
                                {"label": "housing_complex", "value": "housing_complex"}
                            ],
                        },

                        {
                            "label": "Lodging",
                            "value": "Lodging",
                            "children": [
                                {"label": "bed_and_breakfast", "value": "bed_and_breakfast"},
                                {"label": "budget_japanese_inn", "value": "budget_japanese_inn"},
                                {"label": "campground", "value": "campground"},
                                {"label": "camping_cabin", "value": "camping_cabin"},
                                {"label": "cottage", "value": "cottage"},
                                {"label": "extended_stay_hotel", "value": "extended_stay_hotel"},
                                {"label": "farmstay", "value": "farmstay"},
                                {"label": "guest_house hostel", "value": "guest_house hostel"},
                                {"label": "hotel", "value": "hotel"},
                                {"label": "inn", "value": "inn"},
                                {"label": "japanese_inn", "value": "japanese_inn"},
                                {"label": "lodging", "value": "lodging"},
                                {"label": "mobile_home_park", "value": "mobile_home_park"},
                                {"label": "motel", "value": "motel"},
                                {"label": "private_guest_room", "value": "private_guest_room"},
                                {"label": "resort_hotel", "value": "resort_hotel"},
                                {"label": "rv_park", "value": "rv_park"}
                            ],
                        },

                        {
                            "label": "Natural Features",
                            "value": "Natural Features",
                            "children": [
                                {"label": "beach", "value": "beach"}
                            ],
                        },

                        {
                            "label": "Places of Worship",
                            "value": "Places of Worship",
                            "children": [
                                {"label": "church", "value": "church"},
                                {"label": "hindu_temple", "value": "hindu_temple"},
                                {"label": "mosque", "value": "mosque"},
                                {"label": "synagogue", "value": "synagogue"}
                            ],
                        },

                        {
                            "label": "Services",
                            "value": "Services",
                            "children": [
                                {"label": "astrologer", "value": "astrologer"},
                                {"label": "barber_shop", "value": "barber_shop"},
                                {"label": "beautician", "value": "beautician"},
                                {"label": "beauty_salon", "value": "beauty_salon"},
                                {"label": "body_art_service", "value": "body_art_service"},
                                {"label": "catering_service", "value": "catering_service"},
                                {"label": "cemetery", "value": "cemetery"},
                                {"label": "child_care_agency", "value": "child_care_agency"},
                                {"label": "consultant", "value": "consultant"},
                                {"label": "courier_service", "value": "courier_service"},
                                {"label": "electrician", "value": "electrician"},
                                {"label": "florist", "value": "florist"},
                                {"label": "food_delivery", "value": "food_delivery"},
                                {"label": "foot_care", "value": "foot_care"},
                                {"label": "funeral_home", "value": "funeral_home"},
                                {"label": "hair_care", "value": "hair_care"},
                                {"label": "hair_salon", "value": "hair_salon"},
                                {"label": "insurance_agency", "value": "insurance_agency"},
                                {"label": "laundry", "value": "laundry"},
                                {"label": "lawyer", "value": "lawyer"},
                                {"label": "locksmith", "value": "locksmith"},
                                {"label": "makeup_artist", "value": "makeup_artist"},
                                {"label": "moving_company", "value": "moving_company"},
                                {"label": "nail_salon", "value": "nail_salon"},
                                {"label": "painter", "value": "painter"},
                                {"label": "plumber", "value": "plumber"},
                                {"label": "psychic", "value": "psychic"},
                                {"label": "real_estate_agency", "value": "real_estate_agency"},
                                {"label": "roofing_contractor", "value": "roofing_contractor"},
                                {"label": "storage", "value": "storage"},
                                {"label": "summer_camp_organizer", "value": "summer_camp_organizer"},
                                {"label": "tailor", "value": "tailor"},
                                {"label": "telecommunications_service_provider", "value": "telecommunications_service_provider"},
                                {"label": "tour_agency", "value": "tour_agency"},
                                {"label": "tourist_information_center", "value": "tourist_information_center"},
                                {"label": "travel_agency", "value": "travel_agency"}, 
                                {"label": "veterinary_care", "value": "veterinary_care"}
                            ],
                        },

                        {
                            "label": "Shopping",
                            "value": "Shopping",
                            "children": [
                                {"label": "asian_grocery_store", "value": "asian_grocery_store"},
                                {"label": "auto_parts_store", "value": "auto_parts_store"},
                                {"label": "bicycle_store", "value": "bicycle_store"},
                                {"label": "book_store", "value": "book_store"},
                                {"label": "butcher_shop", "value": "butcher_shop"},
                                {"label": "cell_phone_store", "value": "cell_phone_store"},
                                {"label": "clothing_store", "value": "clothing_store"},
                                {"label": "convenience_store", "value": "convenience_store"},
                                {"label": "department_store", "value": "department_store"},
                                {"label": "discount_store", "value": "discount_store"},
                                {"label": "electronics_store", "value": "electronics_store"},
                                {"label": "food_store", "value": "food_store"},
                                {"label": "furniture_store", "value": "furniture_store"},
                                {"label": "gift_shop", "value": "gift_shop"},
                                {"label": "grocery_store", "value": "grocery_store"},
                                {"label": "hardware_store", "value": "hardware_store"},
                                {"label": "home_goods_store", "value": "home_goods_store"},
                                {"label": "home_improvement_store", "value": "home_improvement_store"},
                                {"label": "jewelry_store", "value": "jewelry_store"},
                                {"label": "liquor_store", "value": "liquor_store"},
                                {"label": "market", "value": "market"},
                                {"label": "pet_store", "value": "pet_store"},
                                {"label": "shoe_store", "value": "shoe_store"},
                                {"label": "shopping_mall", "value": "shopping_mall"},
                                {"label": "sporting_goods_store", "value": "sporting_goods_store"},
                                {"label": "store", "value": "store"},
                                {"label": "supermarket", "value": "supermarket"},
                                {"label": "warehouse_store", "value": "warehouse_store"},
                                {"label": "wholesaler", "value": "wholesaler"}
                            ],
                        },

                        {
                            "label": "Sports",
                            "value": "Sports",
                            "children": [
                                {"label": "arena", "value": "arena"},
                                {"label": "athletic_field", "value": "athletic_field"},
                                {"label": "fishing_charter", "value": "fishing_charter"},
                                {"label": "fishing_pond", "value": "fishing_pond"},
                                {"label": "fitness_center", "value": "fitness_center"},
                                {"label": "golf_course", "value": "golf_course"},
                                {"label": "gym", "value": "gym"},
                                {"label": "ice_skating_rink", "value": "ice_skating_rink"},
                                {"label": "playground", "value": "playground"},
                                {"label": "ski_resort", "value": "ski_resort"},
                                {"label": "sports_activity_location", "value": "sports_activity_location"},
                                {"label": "sports_club", "value": "sports_club"},
                                {"label": "sports_coaching", "value": "sports_coaching"},
                                {"label": "sports_complex", "value": "sports_complex"},
                                {"label": "stadium", "value": "stadium"},
                                {"label": "swimming_pool", "value": "swimming_pool"}
                            ],
                        },

                        {
                            "label": "Transportation",
                            "value": "Transportation",
                            "children": [
                                {"label": "airport", "value": "airport"},
                                {"label": "airstrip", "value": "airstrip"},
                                {"label": "bus_station", "value": "bus_station"},
                                {"label": "bus_stop", "value": "bus_stop"},
                                {"label": "ferry_terminal", "value": "ferry_terminal"},
                                {"label": "heliport", "value": "heliport"},
                                {"label": "international_airport", "value": "international_airport"},
                                {"label": "light_rail_station", "value": "light_rail_station"},
                                {"label": "park_and_ride", "value": "park_and_ride"},
                                {"label": "subway_station", "value": "subway_station"},
                                {"label": "taxi_stand", "value": "taxi_stand"},
                                {"label": "train_station", "value": "train_station"},
                                {"label": "transit_depot", "value": "transit_depot"},
                                {"label": "transit_station", "value": "transit_station"},
                                {"label": "truck_stop", "value": "truck_stop"}
                            ],
                        },
                    ],
                },
    ]

    return_select = tree_select(nodes)
    # st.write(return_select)