version: "3.10"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plaid_backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plaid_backend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

