apiVersion: v1                   # API version for the Service resource
kind: Service                    # Defines this resource as a Service
metadata:
  name: frontend                 # Name of the service
spec:
  selector:
    app: frontend                # Label selector to match the pods managed by this service
  ports:
    - protocol: TCP              # Protocol used by the service
      port: 8501                   # Port on which the service is exposed
      targetPort: 8501           # Port on which the container listens
  type: ClusterIP  
