apiVersion: apps/v1              # API version for the Deployment resource
kind: Deployment                 # Defines this resource as a Deployment
metadata:
  name: frontend                 # Name of the deployment
spec:
  replicas: 1                    # Number of pod replicas to run
  selector:
    matchLabels:
      app: frontend              # Label selector to identify the pods managed by this deployment
  template:
    metadata:
      labels:
        app: frontend            # Label applied to the pods for identification
    spec:
      containers:
      - name: frontend           # Name of the container
        image: sofacrcapstone.azurecr.io/frontend:latest  # Container image from Azure Container Registry
        ports:
        - containerPort: 8501    # Port that the container listens on (Streamlit default port)
        resources:
          requests:
            cpu: "200m"        # Reserve 50m CPU for the pod
            memory: "256Mi"    # Reserve 128Mi memory for the pod
          limits:
            memory: "256Mi"
